// GENERATED by @mailda/sdk from packages/contract/src/routes.ts — do not edit.
// One method per route, named <verb><StaticSegments>By<Param>. To change one, change the route and
// re-run `pnpm sdk`. `pnpm sdk:check` fails on any diff. See packages/sdk/src/generate.ts.

import type * as z from "zod";

import * as S from "@mailda/contract/schemas";

import { Transport } from "./transport.ts";

/**
 * Every route this Node serves, as a method.
 *
 * Generated, so the surface is the contract's and drifts from it only by failing `pnpm sdk:check`.
 */
export class GeneratedClient extends Transport {
  /**
   * Whether this Node is up, and what is missing if it is not
   *
   * `GET /health`
   */
  async getHealth(): Promise<z.infer<typeof S.healthResponse>> {
    return await this.json("GET", "/health", {}, undefined) as z.infer<typeof S.healthResponse>;
  }

  /**
   * The interface shell
   *
   * `GET /index.html`
   */
  async getIndexHtml(): Promise<Response> {
    return await this.raw("GET", "/index.html", {}, undefined);
  }

  /**
   * The public keys that verify this Node's tokens
   *
   * `GET /.well-known/jwks.json`
   */
  async getWellKnownJwksJson(): Promise<z.infer<typeof S.jwksResponse>> {
    return await this.json("GET", "/.well-known/jwks.json", {}, undefined) as z.infer<typeof S.jwksResponse>;
  }

  /**
   * Claim an unclaimed Node: the first account and organization
   *
   * `POST /api/claim`
   */
  async postClaim(body?: unknown): Promise<z.infer<typeof S.claimedResponse>> {
    return await this.json("POST", "/api/claim", {}, body) as z.infer<typeof S.claimedResponse>;
  }

  /**
   * Spend an ADR 29 recovery code to restore this Node's key vault
   *
   * `POST /api/recovery/redeem`
   */
  async postRecoveryRedeem(body: z.infer<typeof S.redeemRecoveryRequest>): Promise<z.infer<typeof S.vaultRestoredResponse>> {
    return await this.json("POST", "/api/recovery/redeem", {}, body) as z.infer<typeof S.vaultRestoredResponse>;
  }

  /**
   * Mint a delegated agent, returning its token once
   *
   * `POST /api/agents`
   */
  async postAgents(body: z.infer<typeof S.agentMintRequest>): Promise<z.infer<typeof S.agentMintedResponse>> {
    return await this.json("POST", "/api/agents", {}, body) as z.infer<typeof S.agentMintedResponse>;
  }

  /**
   * Every agent in this organization
   *
   * `GET /api/agents`
   */
  async getAgents(): Promise<z.infer<typeof S.agentListResponse>> {
    return await this.json("GET", "/api/agents", {}, undefined) as z.infer<typeof S.agentListResponse>;
  }

  /**
   * Every mailbox, with what this person holds on each — the mint surface's resource catalogue
   *
   * `GET /api/people/:userId/mailboxes`
   */
  async getPeopleByUserIdMailboxes(params: { userId: string }): Promise<z.infer<typeof S.sponsorMailboxListResponse>> {
    return await this.json("GET", "/api/people/:userId/mailboxes", params, undefined) as z.infer<typeof S.sponsorMailboxListResponse>;
  }

  /**
   * What an agent may be granted, in this Node's own vocabulary
   *
   * `GET /api/agent-capabilities`
   */
  async getAgentCapabilities(): Promise<z.infer<typeof S.agentCapabilityListResponse>> {
    return await this.json("GET", "/api/agent-capabilities", {}, undefined) as z.infer<typeof S.agentCapabilityListResponse>;
  }

  /**
   * Withdraw an agent's credential immediately
   *
   * `DELETE /api/agents/:agentId`
   */
  async deleteAgentsByAgentId(params: { agentId: string }, body?: unknown): Promise<z.infer<typeof S.agentRevokedResponse>> {
    return await this.json("DELETE", "/api/agents/:agentId", params, body) as z.infer<typeof S.agentRevokedResponse>;
  }

  /**
   * Messages the body index failed on, with the reason for each
   *
   * `GET /api/search/failed`
   */
  async getSearchFailed(): Promise<z.infer<typeof S.searchFailedResponse>> {
    return await this.json("GET", "/api/search/failed", {}, undefined) as z.infer<typeof S.searchFailedResponse>;
  }

  /**
   * Put named messages back in the body index's queue
   *
   * `POST /api/search/repair`
   */
  async postSearchRepair(body: z.infer<typeof S.searchRepairRequest>): Promise<z.infer<typeof S.searchRepairedResponse>> {
    return await this.json("POST", "/api/search/repair", {}, body) as z.infer<typeof S.searchRepairedResponse>;
  }

  /**
   * Record that a permanent key collision has been assessed
   *
   * `POST /api/recovery/conflicts/:restoreId/acknowledge`
   */
  async postRecoveryConflictsByRestoreIdAcknowledge(params: { restoreId: string }, body: z.infer<typeof S.acknowledgeConflictRequest>): Promise<z.infer<typeof S.conflictAcknowledgedResponse>> {
    return await this.json("POST", "/api/recovery/conflicts/:restoreId/acknowledge", params, body) as z.infer<typeof S.conflictAcknowledgedResponse>;
  }

  /**
   * Mint a replacement set of ten recovery codes, shown once
   *
   * `POST /api/recovery-codes/rotate`
   */
  async postRecoveryCodesRotate(body?: unknown): Promise<z.infer<typeof S.recoveryCodesMintedResponse>> {
    return await this.json("POST", "/api/recovery-codes/rotate", {}, body) as z.infer<typeof S.recoveryCodesMintedResponse>;
  }

  /**
   * Prove an operator holds one of the current recovery codes, without spending it
   *
   * `POST /api/recovery-codes/confirm`
   */
  async postRecoveryCodesConfirm(body: z.infer<typeof S.redeemRecoveryRequest>): Promise<z.infer<typeof S.recoveryCodesConfirmedResponse>> {
    return await this.json("POST", "/api/recovery-codes/confirm", {}, body) as z.infer<typeof S.recoveryCodesConfirmedResponse>;
  }

  /**
   * Apply pending migrations
   *
   * `POST /api/prepare`
   */
  async postPrepare(body?: unknown): Promise<z.infer<typeof S.prepareResponse>> {
    return await this.json("POST", "/api/prepare", {}, body) as z.infer<typeof S.prepareResponse>;
  }

  /**
   * What this Node can and cannot do, with the evidence
   *
   * `GET /api/doctor`
   */
  async getDoctor(): Promise<z.infer<typeof S.doctorResponse>> {
    return await this.json("GET", "/api/doctor", {}, undefined) as z.infer<typeof S.doctorResponse>;
  }

  /**
   * Exchange a password for a session
   *
   * `POST /api/auth/login`
   */
  async postAuthLogin(body: z.infer<typeof S.loginRequest>): Promise<z.infer<typeof S.signedInResponse>> {
    return await this.json("POST", "/api/auth/login", {}, body) as z.infer<typeof S.signedInResponse>;
  }

  /**
   * Exchange a refresh token for a new access token
   *
   * `POST /api/auth/refresh`
   */
  async postAuthRefresh(body?: unknown): Promise<z.infer<typeof S.refreshedResponse>> {
    return await this.json("POST", "/api/auth/refresh", {}, body) as z.infer<typeof S.refreshedResponse>;
  }

  /**
   * End this session
   *
   * `POST /api/auth/logout`
   */
  async postAuthLogout(body?: unknown): Promise<z.infer<typeof S.signedOutResponse>> {
    return await this.json("POST", "/api/auth/logout", {}, body) as z.infer<typeof S.signedOutResponse>;
  }

  /**
   * End every session this person holds
   *
   * `POST /api/auth/logout-everywhere`
   */
  async postAuthLogoutEverywhere(body?: unknown): Promise<z.infer<typeof S.signedOutResponse>> {
    return await this.json("POST", "/api/auth/logout-everywhere", {}, body) as z.infer<typeof S.signedOutResponse>;
  }

  /**
   * Mint a new token signing key, keeping the old one for the verify grace
   *
   * `POST /api/auth/rotate-signing-key`
   */
  async postAuthRotateSigningKey(body?: unknown): Promise<z.infer<typeof S.keyRotatedResponse>> {
    return await this.json("POST", "/api/auth/rotate-signing-key", {}, body) as z.infer<typeof S.keyRotatedResponse>;
  }

  /**
   * Who this session is
   *
   * `GET /api/me`
   */
  async getMe(): Promise<z.infer<typeof S.meResponse>> {
    return await this.json("GET", "/api/me", {}, undefined) as z.infer<typeof S.meResponse>;
  }

  /**
   * A single-use challenge for either ceremony. Unauthenticated for authentication, which is what keeps it from answering whether an address has a passkey
   *
   * `POST /api/auth/passkeys/challenge`
   */
  async postAuthPasskeysChallenge(body: z.infer<typeof S.passkeyChallengeRequest>): Promise<z.infer<typeof S.passkeyChallengeResponse>> {
    return await this.json("POST", "/api/auth/passkeys/challenge", {}, body) as z.infer<typeof S.passkeyChallengeResponse>;
  }

  /**
   * Finish registration: verify the attestation and store the public key
   *
   * `POST /api/auth/passkeys`
   */
  async postAuthPasskeys(body?: unknown): Promise<z.infer<typeof S.passkeyRegisteredResponse>> {
    return await this.json("POST", "/api/auth/passkeys", {}, body) as z.infer<typeof S.passkeyRegisteredResponse>;
  }

  /**
   * Finish authentication: verify the assertion and issue a session
   *
   * `POST /api/auth/passkeys/verify`
   */
  async postAuthPasskeysVerify(body?: unknown): Promise<z.infer<typeof S.signedInResponse>> {
    return await this.json("POST", "/api/auth/passkeys/verify", {}, body) as z.infer<typeof S.signedInResponse>;
  }

  /**
   * The passkeys this account holds. Never returns a public key
   *
   * `GET /api/auth/passkeys`
   */
  async getAuthPasskeys(): Promise<z.infer<typeof S.passkeyListResponse>> {
    return await this.json("GET", "/api/auth/passkeys", {}, undefined) as z.infer<typeof S.passkeyListResponse>;
  }

  /**
   * Revoke one, bound to its owner by the statement's own predicate
   *
   * `DELETE /api/auth/passkeys`
   */
  async deleteAuthPasskeys(body?: unknown): Promise<z.infer<typeof S.passkeyForgottenResponse>> {
    return await this.json("DELETE", "/api/auth/passkeys", {}, body) as z.infer<typeof S.passkeyForgottenResponse>;
  }

  /**
   * Invitations still outstanding
   *
   * `GET /api/invitations`
   */
  async getInvitations(): Promise<z.infer<typeof S.invitationListResponse>> {
    return await this.json("GET", "/api/invitations", {}, undefined) as z.infer<typeof S.invitationListResponse>;
  }

  /**
   * Invite an address to this organization
   *
   * `POST /api/invitations`
   */
  async postInvitations(body?: unknown): Promise<z.infer<typeof S.invitationCreatedResponse>> {
    return await this.json("POST", "/api/invitations", {}, body) as z.infer<typeof S.invitationCreatedResponse>;
  }

  /**
   * Redeem an invitation by choosing a password
   *
   * `POST /api/invitations/redeem`
   */
  async postInvitationsRedeem(body?: unknown): Promise<z.infer<typeof S.redeemedResponse>> {
    return await this.json("POST", "/api/invitations/redeem", {}, body) as z.infer<typeof S.redeemedResponse>;
  }

  /**
   * Everybody in this organization
   *
   * `GET /api/people`
   */
  async getPeople(): Promise<z.infer<typeof S.peopleListResponse>> {
    return await this.json("GET", "/api/people", {}, undefined) as z.infer<typeof S.peopleListResponse>;
  }

  /**
   * Every team
   *
   * `GET /api/teams`
   */
  async getTeams(): Promise<z.infer<typeof S.teamListResponse>> {
    return await this.json("GET", "/api/teams", {}, undefined) as z.infer<typeof S.teamListResponse>;
  }

  /**
   * Create a team
   *
   * `POST /api/teams`
   */
  async postTeams(body?: unknown): Promise<z.infer<typeof S.teamCreatedResponse>> {
    return await this.json("POST", "/api/teams", {}, body) as z.infer<typeof S.teamCreatedResponse>;
  }

  /**
   * One team
   *
   * `GET /api/teams/:teamId`
   */
  async getTeamsByTeamId(params: { teamId: string }): Promise<z.infer<typeof S.teamDetailResponse>> {
    return await this.json("GET", "/api/teams/:teamId", params, undefined) as z.infer<typeof S.teamDetailResponse>;
  }

  /**
   * Rename a team
   *
   * `POST /api/teams/:teamId/rename`
   */
  async postTeamsByTeamIdRename(params: { teamId: string }, body?: unknown): Promise<z.infer<typeof S.teamCreatedResponse>> {
    return await this.json("POST", "/api/teams/:teamId/rename", params, body) as z.infer<typeof S.teamCreatedResponse>;
  }

  /**
   * Who is in a team
   *
   * `GET /api/teams/:teamId/members`
   */
  async getTeamsByTeamIdMembers(params: { teamId: string }): Promise<z.infer<typeof S.teamMembersResponse>> {
    return await this.json("GET", "/api/teams/:teamId/members", params, undefined) as z.infer<typeof S.teamMembersResponse>;
  }

  /**
   * Put somebody in a team, conferring every relation it holds
   *
   * `POST /api/teams/:teamId/members`
   */
  async postTeamsByTeamIdMembers(params: { teamId: string }, body?: unknown): Promise<z.infer<typeof S.teamMembershipResponse>> {
    return await this.json("POST", "/api/teams/:teamId/members", params, body) as z.infer<typeof S.teamMembershipResponse>;
  }

  /**
   * Take somebody out of a team, effective on their next request
   *
   * `DELETE /api/teams/:teamId/members`
   */
  async deleteTeamsByTeamIdMembers(params: { teamId: string }, body?: unknown): Promise<z.infer<typeof S.teamMembershipResponse>> {
    return await this.json("DELETE", "/api/teams/:teamId/members", params, body) as z.infer<typeof S.teamMembershipResponse>;
  }

  /**
   * Who holds what on which mailbox
   *
   * `GET /api/access`
   */
  async getAccess(): Promise<z.infer<typeof S.accessResponse>> {
    return await this.json("GET", "/api/access", {}, undefined) as z.infer<typeof S.accessResponse>;
  }

  /**
   * Grant a relation on a mailbox
   *
   * `POST /api/access`
   */
  async postAccess(body?: unknown): Promise<z.infer<typeof S.grantedResponse>> {
    return await this.json("POST", "/api/access", {}, body) as z.infer<typeof S.grantedResponse>;
  }

  /**
   * Revoke a relation on a mailbox
   *
   * `DELETE /api/access`
   */
  async deleteAccess(body?: unknown): Promise<z.infer<typeof S.revokedResponse>> {
    return await this.json("DELETE", "/api/access", {}, body) as z.infer<typeof S.revokedResponse>;
  }

  /**
   * Live supervised-access grants (§7)
   *
   * `GET /api/supervised`
   */
  async getSupervised(): Promise<z.infer<typeof S.supervisedListResponse>> {
    return await this.json("GET", "/api/supervised", {}, undefined) as z.infer<typeof S.supervisedListResponse>;
  }

  /**
   * Grant supervised access, which expires
   *
   * `POST /api/supervised`
   */
  async postSupervised(body?: unknown): Promise<z.infer<typeof S.supervisedRequestedResponse>> {
    return await this.json("POST", "/api/supervised", {}, body) as z.infer<typeof S.supervisedRequestedResponse>;
  }

  /**
   * The mailboxes this person may act in
   *
   * `GET /api/mailboxes`
   */
  async getMailboxes(): Promise<z.infer<typeof S.mailboxListResponse>> {
    return await this.json("GET", "/api/mailboxes", {}, undefined) as z.infer<typeof S.mailboxListResponse>;
  }

  /**
   * Change a mailbox's settings
   *
   * `PATCH /api/mailboxes/:mailboxId`
   */
  async patchMailboxesByMailboxId(params: { mailboxId: string }, body?: unknown): Promise<z.infer<typeof S.mailboxPatchedResponse>> {
    return await this.json("PATCH", "/api/mailboxes/:mailboxId", params, body) as z.infer<typeof S.mailboxPatchedResponse>;
  }

  /**
   * Message metadata, newest first, one page at a time. Pass the previous page's next_cursor to continue; null means nothing older is visible
   *
   * @param query.cursor The previous page's next_cursor, verbatim. Omit for the newest page.
   *
   * @param query.mailbox Only this mailbox's mail. Omit for every mailbox you may read.
   *
   * @param query.q Words that must all appear in the subject or sender address. The last word matches as a prefix, so a part-typed word narrows. Not a query language: operators are read as words.
   *
   * `GET /api/messages`
   */
  async getMessages(query?: { cursor?: string; mailbox?: string; q?: string }): Promise<z.infer<typeof S.messageListResponse>> {
    return await this.json("GET", "/api/messages", {}, undefined, query) as z.infer<typeof S.messageListResponse>;
  }

  /**
   * One message's rendered body. Takes the receipt id that GET /api/messages returns as `id`
   *
   * `GET /api/messages/:receiptId/body`
   */
  async getMessagesByReceiptIdBody(params: { receiptId: string }): Promise<z.infer<typeof S.messageBodyResponse>> {
    return await this.json("GET", "/api/messages/:receiptId/body", params, undefined) as z.infer<typeof S.messageBodyResponse>;
  }

  /**
   * One message's stored bytes, as message/rfc822. Takes the receipt id, as the body route does
   *
   * `GET /api/messages/:receiptId/raw`
   */
  async getMessagesByReceiptIdRaw(params: { receiptId: string }): Promise<Response> {
    return await this.raw("GET", "/api/messages/:receiptId/raw", params, undefined);
  }

  /**
   * What has changed since the last poll
   *
   * `GET /api/notifications`
   */
  async getNotifications(): Promise<z.infer<typeof S.notificationListResponse>> {
    return await this.json("GET", "/api/notifications", {}, undefined) as z.infer<typeof S.notificationListResponse>;
  }

  /**
   * Mailboxes this caller may read, which is not the work-queue list
   *
   * `GET /api/mailboxes/readable`
   */
  async getMailboxesReadable(): Promise<z.infer<typeof S.readableMailboxListResponse>> {
    return await this.json("GET", "/api/mailboxes/readable", {}, undefined) as z.infer<typeof S.readableMailboxListResponse>;
  }

  /**
   * The case queue in one mailbox
   *
   * `GET /api/mailboxes/:mailboxId/cases`
   */
  async getMailboxesByMailboxIdCases(params: { mailboxId: string }): Promise<z.infer<typeof S.caseListResponse>> {
    return await this.json("GET", "/api/mailboxes/:mailboxId/cases", params, undefined) as z.infer<typeof S.caseListResponse>;
  }

  /**
   * Claim, steal, release or close a case
   *
   * `POST /api/cases/:caseId/:action`
   */
  async postCasesByCaseIdByAction(params: { caseId: string; action: string }, body?: unknown): Promise<z.infer<typeof S.caseActionResponse>> {
    return await this.json("POST", "/api/cases/:caseId/:action", params, body) as z.infer<typeof S.caseActionResponse>;
  }

  /**
   * Merge two conversations into one
   *
   * `POST /api/conversations/merge`
   */
  async postConversationsMerge(body?: unknown): Promise<z.infer<typeof S.conversationMergedResponse>> {
    return await this.json("POST", "/api/conversations/merge", {}, body) as z.infer<typeof S.conversationMergedResponse>;
  }

  /**
   * Drafts this person is writing
   *
   * `GET /api/drafts`
   */
  async getDrafts(): Promise<z.infer<typeof S.draftListResponse>> {
    return await this.json("GET", "/api/drafts", {}, undefined) as z.infer<typeof S.draftListResponse>;
  }

  /**
   * Save a draft
   *
   * `PUT /api/drafts`
   */
  async putDrafts(body: z.infer<typeof S.saveDraftRequest>): Promise<z.infer<typeof S.draftSavedResponse>> {
    return await this.json("PUT", "/api/drafts", {}, body) as z.infer<typeof S.draftSavedResponse>;
  }

  /**
   * One draft
   *
   * `GET /api/drafts/:draftId`
   */
  async getDraftsByDraftId(params: { draftId: string }): Promise<z.infer<typeof S.draftDetailResponse>> {
    return await this.json("GET", "/api/drafts/:draftId", params, undefined) as z.infer<typeof S.draftDetailResponse>;
  }

  /**
   * Discard a draft
   *
   * `DELETE /api/drafts/:draftId`
   */
  async deleteDraftsByDraftId(params: { draftId: string }, body?: unknown): Promise<z.infer<typeof S.draftDeletedResponse>> {
    return await this.json("DELETE", "/api/drafts/:draftId", params, body) as z.infer<typeof S.draftDeletedResponse>;
  }

  /**
   * The outbox
   *
   * `GET /api/sends`
   */
  async getSends(): Promise<z.infer<typeof S.sendListResponse>> {
    return await this.json("GET", "/api/sends", {}, undefined) as z.infer<typeof S.sendListResponse>;
  }

  /**
   * Seal a manifest: the act that commits a send to policy
   *
   * `POST /api/sends`
   */
  async postSends(body?: unknown): Promise<z.infer<typeof S.sendSealedResponse>> {
    return await this.json("POST", "/api/sends", {}, body) as z.infer<typeof S.sendSealedResponse>;
  }

  /**
   * Hand every due send to the transport now
   *
   * `POST /api/sends/dispatch`
   */
  async postSendsDispatch(body?: unknown): Promise<z.infer<typeof S.dispatchResponse>> {
    return await this.json("POST", "/api/sends/dispatch", {}, body) as z.infer<typeof S.dispatchResponse>;
  }

  /**
   * Cancel a send that has not left
   *
   * `POST /api/sends/:sendId/cancel`
   */
  async postSendsBySendIdCancel(params: { sendId: string }, body?: unknown): Promise<z.infer<typeof S.sendCancelledResponse>> {
    return await this.json("POST", "/api/sends/:sendId/cancel", params, body) as z.infer<typeof S.sendCancelledResponse>;
  }

  /**
   * Retry a send that failed
   *
   * `POST /api/sends/:sendId/retry`
   */
  async postSendsBySendIdRetry(params: { sendId: string }, body?: unknown): Promise<z.infer<typeof S.sendRetriedResponse>> {
    return await this.json("POST", "/api/sends/:sendId/retry", params, body) as z.infer<typeof S.sendRetriedResponse>;
  }

  /**
   * Release a send parked on a Butler's gate
   *
   * `POST /api/sends/:sendId/release`
   */
  async postSendsBySendIdRelease(params: { sendId: string }, body?: unknown): Promise<z.infer<typeof S.sendReleasedResponse>> {
    return await this.json("POST", "/api/sends/:sendId/release", params, body) as z.infer<typeof S.sendReleasedResponse>;
  }

  /**
   * Release a send a policy put on hold
   *
   * `POST /api/sends/:sendId/release-hold`
   */
  async postSendsBySendIdReleaseHold(params: { sendId: string }, body?: unknown): Promise<z.infer<typeof S.sendHoldReleasedResponse>> {
    return await this.json("POST", "/api/sends/:sendId/release-hold", params, body) as z.infer<typeof S.sendHoldReleasedResponse>;
  }

  /**
   * The exact bytes handed to the transport, as the message itself
   *
   * `GET /api/sends/:sendId/submitted`
   */
  async getSendsBySendIdSubmitted(params: { sendId: string }): Promise<Response> {
    return await this.raw("GET", "/api/sends/:sendId/submitted", params, undefined);
  }

  /**
   * Every policy, with the version that is live
   *
   * `GET /api/policies`
   */
  async getPolicies(): Promise<z.infer<typeof S.policyListResponse>> {
    return await this.json("GET", "/api/policies", {}, undefined) as z.infer<typeof S.policyListResponse>;
  }

  /**
   * Create a policy
   *
   * `POST /api/policies`
   */
  async postPolicies(body: z.infer<typeof S.createPolicyRequest>): Promise<z.infer<typeof S.policyDraftResponse>> {
    return await this.json("POST", "/api/policies", {}, body) as z.infer<typeof S.policyDraftResponse>;
  }

  /**
   * Replace a policy's draft
   *
   * `PUT /api/policies/:policyId/draft`
   */
  async putPoliciesByPolicyIdDraft(params: { policyId: string }, body: z.infer<typeof S.editPolicyDraftRequest>): Promise<z.infer<typeof S.policyDraftResponse>> {
    return await this.json("PUT", "/api/policies/:policyId/draft", params, body) as z.infer<typeof S.policyDraftResponse>;
  }

  /**
   * Publish a policy's draft, which is the versioning event
   *
   * `POST /api/policies/:policyId/publish`
   */
  async postPoliciesByPolicyIdPublish(params: { policyId: string }, body?: unknown): Promise<z.infer<typeof S.policyPublishedResponse>> {
    return await this.json("POST", "/api/policies/:policyId/publish", params, body) as z.infer<typeof S.policyPublishedResponse>;
  }

  /**
   * Approvals waiting on somebody
   *
   * `GET /api/approvals`
   */
  async getApprovals(): Promise<z.infer<typeof S.approvalListResponse>> {
    return await this.json("GET", "/api/approvals", {}, undefined) as z.infer<typeof S.approvalListResponse>;
  }

  /**
   * Approve or refuse a send
   *
   * `POST /api/approvals/:approvalId/decide`
   */
  async postApprovalsByApprovalIdDecide(params: { approvalId: string }, body?: unknown): Promise<z.infer<typeof S.approvalDecidedResponse>> {
    return await this.json("POST", "/api/approvals/:approvalId/decide", params, body) as z.infer<typeof S.approvalDecidedResponse>;
  }

  /**
   * Withdraw your own decision on a request
   *
   * `POST /api/approvals/:approvalId/withdraw`
   */
  async postApprovalsByApprovalIdWithdraw(params: { approvalId: string }, body?: unknown): Promise<z.infer<typeof S.approvalWithdrawnResponse>> {
    return await this.json("POST", "/api/approvals/:approvalId/withdraw", params, body) as z.infer<typeof S.approvalWithdrawnResponse>;
  }

  /**
   * Legal holds in force
   *
   * `GET /api/holds`
   */
  async getHolds(): Promise<z.infer<typeof S.holdListResponse>> {
    return await this.json("GET", "/api/holds", {}, undefined) as z.infer<typeof S.holdListResponse>;
  }

  /**
   * Place a legal hold
   *
   * `POST /api/holds`
   */
  async postHolds(body?: unknown): Promise<z.infer<typeof S.holdPlacedResponse>> {
    return await this.json("POST", "/api/holds", {}, body) as z.infer<typeof S.holdPlacedResponse>;
  }

  /**
   * Lift a legal hold, which takes more than one person
   *
   * `POST /api/holds/:holdId/lift`
   */
  async postHoldsByHoldIdLift(params: { holdId: string }, body?: unknown): Promise<z.infer<typeof S.holdLiftRequestedResponse>> {
    return await this.json("POST", "/api/holds/:holdId/lift", params, body) as z.infer<typeof S.holdLiftRequestedResponse>;
  }

  /**
   * Matters a hold or an export can be scoped to
   *
   * `GET /api/matters`
   */
  async getMatters(): Promise<z.infer<typeof S.matterListResponse>> {
    return await this.json("GET", "/api/matters", {}, undefined) as z.infer<typeof S.matterListResponse>;
  }

  /**
   * Open a matter
   *
   * `POST /api/matters`
   */
  async postMatters(body: z.infer<typeof S.openMatterRequest>): Promise<z.infer<typeof S.matterResponse>> {
    return await this.json("POST", "/api/matters", {}, body) as z.infer<typeof S.matterResponse>;
  }

  /**
   * Close a matter
   *
   * `POST /api/matters/:matterId/close`
   */
  async postMattersByMatterIdClose(params: { matterId: string }, body?: unknown): Promise<z.infer<typeof S.matterResponse>> {
    return await this.json("POST", "/api/matters/:matterId/close", params, body) as z.infer<typeof S.matterResponse>;
  }

  /**
   * The rate breakers, with the readings behind them
   *
   * `GET /api/breakers`
   */
  async getBreakers(): Promise<z.infer<typeof S.breakerListResponse>> {
    return await this.json("GET", "/api/breakers", {}, undefined) as z.infer<typeof S.breakerListResponse>;
  }

  /**
   * Domains this Node has stopped sending to
   *
   * `GET /api/domain-pauses`
   */
  async getDomainPauses(): Promise<z.infer<typeof S.domainPauseListResponse>> {
    return await this.json("GET", "/api/domain-pauses", {}, undefined) as z.infer<typeof S.domainPauseListResponse>;
  }

  /**
   * Stop sending to a domain
   *
   * `POST /api/domain-pauses`
   */
  async postDomainPauses(body?: unknown): Promise<z.infer<typeof S.domainPauseRequestedResponse>> {
    return await this.json("POST", "/api/domain-pauses", {}, body) as z.infer<typeof S.domainPauseRequestedResponse>;
  }

  /**
   * Resume sending to a domain, which takes more than one person
   *
   * `POST /api/domain-pauses/:pauseId/lift`
   */
  async postDomainPausesByPauseIdLift(params: { pauseId: string }, body?: unknown): Promise<z.infer<typeof S.domainPauseLiftedResponse>> {
    return await this.json("POST", "/api/domain-pauses/:pauseId/lift", params, body) as z.infer<typeof S.domainPauseLiftedResponse>;
  }

  /**
   * Every Butler, with the version that is live
   *
   * `GET /api/butlers`
   */
  async getButlers(): Promise<z.infer<typeof S.butlerListResponse>> {
    return await this.json("GET", "/api/butlers", {}, undefined) as z.infer<typeof S.butlerListResponse>;
  }

  /**
   * Create a Butler and its first draft
   *
   * `POST /api/butlers`
   */
  async postButlers(body: z.infer<typeof S.createButlerRequest>): Promise<z.infer<typeof S.butlerDraftResponse>> {
    return await this.json("POST", "/api/butlers", {}, body) as z.infer<typeof S.butlerDraftResponse>;
  }

  /**
   * One Butler and its version history
   *
   * `GET /api/butlers/:butlerId`
   */
  async getButlersByButlerId(params: { butlerId: string }): Promise<z.infer<typeof S.butlerDetailResponse>> {
    return await this.json("GET", "/api/butlers/:butlerId", params, undefined) as z.infer<typeof S.butlerDetailResponse>;
  }

  /**
   * Replace a Butler's draft
   *
   * `PUT /api/butlers/:butlerId/draft`
   */
  async putButlersByButlerIdDraft(params: { butlerId: string }, body: z.infer<typeof S.editButlerDraftRequest>): Promise<z.infer<typeof S.butlerDraftResponse>> {
    return await this.json("PUT", "/api/butlers/:butlerId/draft", params, body) as z.infer<typeof S.butlerDraftResponse>;
  }

  /**
   * Publish a Butler's draft, which is the versioning event
   *
   * `POST /api/butlers/:butlerId/publish`
   */
  async postButlersByButlerIdPublish(params: { butlerId: string }, body?: unknown): Promise<z.infer<typeof S.butlerPublishedResponse>> {
    return await this.json("POST", "/api/butlers/:butlerId/publish", params, body) as z.infer<typeof S.butlerPublishedResponse>;
  }

  /**
   * Dry-run a Butler: walk it, cause nothing, report what a live run would do
   *
   * `POST /api/butlers/:butlerId/simulate`
   */
  async postButlersByButlerIdSimulate(params: { butlerId: string }, body: z.infer<typeof S.simulateRequest>): Promise<z.infer<typeof S.simulationResponse>> {
    return await this.json("POST", "/api/butlers/:butlerId/simulate", params, body) as z.infer<typeof S.simulationResponse>;
  }

  /**
   * What the Butlers have done
   *
   * `GET /api/butler-runs`
   */
  async getButlerRuns(): Promise<z.infer<typeof S.butlerRunListResponse>> {
    return await this.json("GET", "/api/butler-runs", {}, undefined) as z.infer<typeof S.butlerRunListResponse>;
  }

  /**
   * One run
   *
   * `GET /api/butler-runs/:runId`
   */
  async getButlerRunsByRunId(params: { runId: string }): Promise<z.infer<typeof S.butlerRunDetailResponse>> {
    return await this.json("GET", "/api/butler-runs/:runId", params, undefined) as z.infer<typeof S.butlerRunDetailResponse>;
  }

  /**
   * One run's input, program and effects, with the replay modes it offers
   *
   * `GET /api/butler-runs/:runId/inspect`
   */
  async getButlerRunsByRunIdInspect(params: { runId: string }): Promise<z.infer<typeof S.butlerRunInspectionResponse>> {
    return await this.json("GET", "/api/butler-runs/:runId/inspect", params, undefined) as z.infer<typeof S.butlerRunInspectionResponse>;
  }

  /**
   * Replay a run in a named mode
   *
   * `POST /api/butler-runs/:runId/replay`
   */
  async postButlerRunsByRunIdReplay(params: { runId: string }, body?: unknown): Promise<z.infer<typeof S.butlerRunReplayedResponse>> {
    return await this.json("POST", "/api/butler-runs/:runId/replay", params, body) as z.infer<typeof S.butlerRunReplayedResponse>;
  }

  /**
   * Butlers a machine has stopped
   *
   * `GET /api/butler-pauses`
   */
  async getButlerPauses(): Promise<z.infer<typeof S.butlerPauseListResponse>> {
    return await this.json("GET", "/api/butler-pauses", {}, undefined) as z.infer<typeof S.butlerPauseListResponse>;
  }

  /**
   * Restart a stopped Butler, with a reason
   *
   * `POST /api/butler-pauses/:pauseId/resume`
   */
  async postButlerPausesByPauseIdResume(params: { pauseId: string }, body?: unknown): Promise<z.infer<typeof S.butlerPauseResumedResponse>> {
    return await this.json("POST", "/api/butler-pauses/:pauseId/resume", params, body) as z.infer<typeof S.butlerPauseResumedResponse>;
  }

  /**
   * The audit trail
   *
   * `GET /api/audit`
   */
  async getAudit(): Promise<z.infer<typeof S.auditListResponse>> {
    return await this.json("GET", "/api/audit", {}, undefined) as z.infer<typeof S.auditListResponse>;
  }

  /**
   * Verify the audit chain
   *
   * `POST /api/audit/verify`
   */
  async postAuditVerify(body?: unknown): Promise<z.infer<typeof S.auditVerifyResponse>> {
    return await this.json("POST", "/api/audit/verify", {}, body) as z.infer<typeof S.auditVerifyResponse>;
  }

  /**
   * Check that stored evidence still matches the hashes recorded at ingress
   *
   * `POST /api/evidence/verify`
   */
  async postEvidenceVerify(body?: unknown): Promise<z.infer<typeof S.evidenceVerifyResponse>> {
    return await this.json("POST", "/api/evidence/verify", {}, body) as z.infer<typeof S.evidenceVerifyResponse>;
  }

  /**
   * Every stored object with the hash its plaintext should have, for a restorable backup
   *
   * `GET /api/evidence/inventory`
   */
  async getEvidenceInventory(): Promise<z.infer<typeof S.evidenceInventoryResponse>> {
    return await this.json("GET", "/api/evidence/inventory", {}, undefined) as z.infer<typeof S.evidenceInventoryResponse>;
  }

  /**
   * The operational log
   *
   * `GET /api/logs`
   */
  async getLogs(): Promise<z.infer<typeof S.logListResponse>> {
    return await this.json("GET", "/api/logs", {}, undefined) as z.infer<typeof S.logListResponse>;
  }

  /**
   * Export jobs
   *
   * `GET /api/exports`
   */
  async getExports(): Promise<z.infer<typeof S.exportListResponse>> {
    return await this.json("GET", "/api/exports", {}, undefined) as z.infer<typeof S.exportListResponse>;
  }

  /**
   * Start an e-discovery export
   *
   * `POST /api/exports`
   */
  async postExports(body?: unknown): Promise<z.infer<typeof S.exportRequestedResponse>> {
    return await this.json("POST", "/api/exports", {}, body) as z.infer<typeof S.exportRequestedResponse>;
  }

  /**
   * Advance an export
   *
   * `POST /api/exports/:exportId/run`
   */
  async postExportsByExportIdRun(params: { exportId: string }, body?: unknown): Promise<z.infer<typeof S.exportRunResponse>> {
    return await this.json("POST", "/api/exports/:exportId/run", params, body) as z.infer<typeof S.exportRunResponse>;
  }

  /**
   * One object from a completed export
   *
   * `GET /api/exports/:exportId/objects/:objectId`
   */
  async getExportsByExportIdObjectsByObjectId(params: { exportId: string; objectId: string }): Promise<Response> {
    return await this.raw("GET", "/api/exports/:exportId/objects/:objectId", params, undefined);
  }

  /**
   * Which adapter carries this Node's mail, and what both can say about themselves
   *
   * `GET /api/transport`
   */
  async getTransport(): Promise<z.infer<typeof S.transportResponse>> {
    return await this.json("GET", "/api/transport", {}, undefined) as z.infer<typeof S.transportResponse>;
  }

  /**
   * Supply the Cloudflare account id and Email Sending API token. The token is never returned
   *
   * `PUT /api/transport`
   */
  async putTransport(body: z.infer<typeof S.transportRequest>): Promise<z.infer<typeof S.transportConfiguredResponse>> {
    return await this.json("PUT", "/api/transport", {}, body) as z.infer<typeof S.transportConfiguredResponse>;
  }

  /**
   * MCP: tool discovery and invocation over JSON-RPC 2.0, exposing the curated capability list
   *
   * `POST /mcp`
   */
  async postMcp(body?: unknown): Promise<unknown> {
    return await this.json("POST", "/mcp", {}, body) as unknown;
  }

  /**
   * Reseal evidence under the current key
   *
   * `POST /api/maintenance/reseal`
   */
  async postMaintenanceReseal(body?: unknown): Promise<z.infer<typeof S.resealResponse>> {
    return await this.json("POST", "/api/maintenance/reseal", {}, body) as z.infer<typeof S.resealResponse>;
  }

  /**
   * Reconcile stored evidence against its metadata
   *
   * `POST /api/maintenance/reconcile`
   */
  async postMaintenanceReconcile(body?: unknown): Promise<z.infer<typeof S.reconcileResponse>> {
    return await this.json("POST", "/api/maintenance/reconcile", {}, body) as z.infer<typeof S.reconcileResponse>;
  }
}
