import { agentCapabilities, withheldCapabilities } from "@mailda/contract/agent";

import { methodNameFor } from "./generate.ts";

/**
 * The Agent Skill, emitted from the curated capability list (#88, ADR 12).
 *
 * ## What a Skill is here, and what it is not
 *
 * Not a second client. `@mailda/sdk` is the client, and a Skill that reimplemented it would be the sixth
 * hand-kept surface ADR 12 exists to prevent. This emits a **document**: what a machine may do with a
 * Mailda Node, in the vocabulary of the product rather than of its routes, plus the SDK method that does
 * each thing.
 *
 * ## Why it names what it withholds
 *
 * The tempting shape is a list of what is offered. That leaves every excluded act as an *absence*, and an
 * agent meeting an absence infers a gap rather than a decision — then goes looking for the route directly,
 * which is precisely the behaviour the curation exists to prevent.
 *
 * So the withheld list ships too, with the reason. An agent that knows *"approving a send needs a second
 * person and you are acting as the first"* stops; one that finds nothing about approvals tries.
 */
export function emitSkill(): string {
  const offered = agentCapabilities(methodNameFor);
  const withheld = withheldCapabilities(methodNameFor);
  const byTier = (tier: string) => withheld.filter((entry) => entry.tier === tier);
  /*
   * The fourth group, and it had no section until it had members.
   *
   * `withheldCapabilities` used to mean "wrong exposure tier" and the document's three headings covered it
   * exactly. Once the offered list began filtering on whether a machine can be *provisioned* for a route,
   * twenty-two ordinary reads and acts joined the withheld total and were rendered by none of the three —
   * counted in the header and absent from the body, which is the shape of gap this Skill exists to close.
   */
  const unprovisionable = withheld
    .filter((entry) => entry.tier === "read" || entry.tier === "act");

  const reasons = new Map<string, string[]>();
  for (const entry of withheld) {
    const list = reasons.get(entry.why) ?? [];
    list.push(entry.name);
    reasons.set(entry.why, list);
  }

  return `---
name: mailda
description: >-
  Read and work in a Mailda Node — a customer-owned mail system running in their own Cloudflare account.
  Answer questions about mail, cases, Butlers and the outbox; write drafts and Butler programs; never send.
---

# Working with a Mailda Node

GENERATED by @mailda/sdk from the route registry and its curation. Do not edit — change
\`packages/contract/src/agent.ts\` and re-run \`pnpm skill\`.

Mailda is one Cloudflare Worker deployed into the customer's own account. Their mail, their keys, their
data. Everything below goes through \`@mailda/sdk\`, whose methods are generated from the same registry this
document is, so a capability listed here exists and one that is not listed does not.

## How to call it

\`\`\`ts
import { createClient } from "@mailda/sdk";

const mailda = createClient({ origin: "https://mail.example.com", headers: { cookie } });
const inbox = await mailda.getMessages();
\`\`\`

Responses are validated against the contract, so a field you read is a field the Node returned. A refusal
arrives as a \`MaildaError\` carrying \`code\`, and its message has three parts — what happened, why, and what
to do. **Read the \`fix\` before retrying.** Most refusals here are not transient and retrying will not help.

## What you can do — ${offered.length} capabilities

${["read", "act"].map((tier) => {
    const group = offered.filter((one) => one.tier === tier);
    const heading = tier === "read"
      ? "### Reading — answers a question, changes nothing"
      : "### Acting — changes something a person can undo";
    return `${heading}\n\n| method | what it does |\n|:--|:--|\n${
      group.map((one) => `| \`${one.name}\` | ${one.summary} |`).join("\n")
    }`;
  }).join("\n\n")}

## What you cannot do, and why — ${withheld.length} withheld

This list is here on purpose. An act missing from a Skill reads as a gap somebody forgot; an act listed as
withheld, with a reason, reads as a decision. **Do not look for another route to these.** The Node refuses
them independently of this document.

### Governed — needs more than one person, or cannot be undone (${byTier("governed").length})

You are acting inside one person's session. Mailda counts **distinct people**, not credentials or requests,
so you are that one person and can never be the second. These are not permissions you might be granted.

${[...reasons.entries()]
    .filter(([, names]) => names.some((name) => byTier("governed").some((entry) => entry.name === name)))
    .map(([why, names]) => `- **${names.map((name) => `\`${name}\``).join(", ")}**\n\n  ${why.replace(/\n\n/g, "\n\n  ")}`)
    .join("\n\n")}

### Operator — running the Node rather than using it (${byTier("operator").length})

${[...reasons.entries()]
    .filter(([, names]) => names.some((name) => byTier("operator").some((entry) => entry.name === name)))
    .map(([why, names]) => `- **${names.map((name) => `\`${name}\``).join(", ")}**\n\n  ${why.replace(/\n\n/g, "\n\n  ")}`)
    .join("\n\n")}

### Out of reach — an ordinary act, and no credential can be provisioned for it (${unprovisionable.length})

These are not governed and not operator acts. They are reads and reversible writes a machine could perfectly
well be trusted with, and there is **no credential that satisfies them**: they require \`org.admin\`, or they
belong to whoever requested an export, or they narrow their answer by a relation no mint confers — so a token
holding them would be admitted and shown nothing, for ever.

They are listed because the alternative is worse. Until now they were counted as withheld and printed
nowhere, which reads as an omission somebody will try to work around. Asking an administrator to grant one of
these does not help; the answer is a person doing it, or a change to what Mailda is willing to delegate.

${[...reasons.entries()]
    .filter(([, names]) => names.some((name) => unprovisionable.some((entry) => entry.name === name)))
    .map(([why, names]) => `- **${names.map((name) => `\`${name}\``).join(", ")}**\n\n  ${why.replace(/\n\n/g, "\n\n  ")}`)
    .join("\n\n")}

## Three things worth knowing before you act

**A draft is not a send.** Writing one is yours to do; committing it to policy is not. \`putDrafts\` saves
text a person will review. \`postSends\` — which you do not have — is the act that commits a message to
leaving, and it is the one act in this product nobody can undo.

**A Butler can be tried without being trusted.** \`postButlersByButlerIdSimulate\` walks a program over a real
past delivery, causes nothing, and reports what a live run would have done — including who a reply would
have gone to. It is the right way to answer *"would this work"*, and it is offered precisely because it
cannot write. Publishing the Butler is not.

**Refusals are written to be acted on.** Every one names the budget or the rule, the reason it exists, and
what would change it. A refusal saying *"ask somebody who holds approval.decide"* is addressed to a person
who can go and ask — if you are reading it, the answer is to report it, not to retry.
`;
}
