import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

/**
 * Lint exists here for one job that nothing else can do.
 *
 * The type checker cannot see the ambient-primitives seam (#6). `Date.now()` and `Math.random()` are
 * perfectly typed — what makes them wrong in a Worker is *where* they appear, and only a syntactic
 * rule can say that. `packages/runtime/src/ctx.ts` has claimed since it was written that "lint bans
 * the bare calls everywhere except this file", and until now nothing did: there was no eslint in the
 * repository at all, and `turbo lint` exited 0 having run zero tasks.
 *
 * That is the shape AGENTS.md calls a landmine — a check that reads as passing because it does not
 * exist. The rules below are deliberately few: this config enforces invariants the compiler cannot,
 * and declines to have opinions about style, which is what makes it worth keeping green.
 */

/** The bare calls the seam exists to replace. Reached through `ctx` so #27 can freeze them. */
const AMBIENT_PRIMITIVES = [
  {
    selector: "CallExpression[callee.object.name='Date'][callee.property.name='now']",
    message:
      "Date.now() bypasses the ctx seam (#6). Use ctx.now(). Workers reuse isolates across requests, " +
      "so an ambient clock leaks one request's time into another's, and §27 replay cannot freeze it.",
  },
  {
    selector: "CallExpression[callee.object.name='Math'][callee.property.name='random']",
    message:
      "Math.random() bypasses the ctx seam (#6) and is not cryptographically secure. Use ctx.random().",
  },
  {
    selector: "CallExpression[callee.object.name='crypto'][callee.property.name='randomUUID']",
    message:
      "crypto.randomUUID() bypasses the ctx seam (#6). Use ctx.id(prefix) — identifiers here are " +
      "typed-prefix ULIDs, which sort by time and say what they are.",
  },
  {
    selector: "NewExpression[callee.name='Date'][arguments.length=0]",
    message:
      "new Date() reads the ambient clock. Use new Date(ctx.now()) so §27 replay can freeze it.",
  },
];

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.wrangler/**",
      // Generated by wrangler from the deployed bindings; thousands of lines, not ours to edit.
      "apps/node/worker/worker-configuration.d.ts",
      // Generated by `pnpm receipts` from docs/receipts. Editing it is the thing the pipeline prevents.
      "packages/budgets/src/generated.ts",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.worker },
    },
    rules: {
      // Unused arguments are how a handler signature documents what it is handed, so only leading
      // ones are worth flagging, and an underscore is the stated way to say "deliberately unused".
      "@typescript-eslint/no-unused-vars": [
        "error",
        { args: "after-used", argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "no-restricted-syntax": ["error", ...AMBIENT_PRIMITIVES],
    },
  },

  /**
   * Ambient type declarations. The triple-slash reference is how `@cloudflare/vitest-pool-workers`
   * publishes its `cloudflare:test` module types — an `import` does not pull in ambient declarations,
   * so the rule's suggested fix silently removes the types rather than modernising them.
   */
  {
    files: ["**/*.d.ts"],
    rules: { "@typescript-eslint/triple-slash-reference": "off" },
  },

  /**
   * Repository tooling that runs in Node on CI, not in a Worker. The ctx seam does not apply: there is
   * no request, no reused isolate, and nothing for §27 to replay.
   */
  {
    files: [".github/scripts/**/*.mjs", "*.config.js"],
    languageOptions: { globals: { ...globals.node } },
    rules: { "no-restricted-syntax": "off" },
  },

  /**
   * Browser code. The ctx seam is a Worker concern — it exists because isolates are reused across
   * requests and because §27 replays server behaviour. A page has one user, one tab and one clock,
   * and `Date.now()` there is the correct call, not a bypass.
   */
  {
    files: ["apps/node/worker/src/client/**/*.js"],
    languageOptions: { globals: { ...globals.browser } },
    rules: { "no-restricted-syntax": "off" },
  },

  /**
   * Tests and benches. A test that pins behaviour to a real elapsed time, or asks what the wall clock
   * says in order to compare against a token's expiry, is measuring rather than bypassing — and the
   * frozen-clock helpers exist for the cases that are not.
   */
  {
    files: ["**/test/**", "**/bench/**", "**/*.test.ts", "**/*.bench.ts"],
    languageOptions: { globals: { ...globals.node } },
    rules: { "no-restricted-syntax": "off" },
  },
);
