/// <reference path="./node_modules/@cloudflare/vitest-pool-workers/types/cloudflare-test.d.ts" />

// `Env` is generated by `wrangler types` into worker-configuration.d.ts and never
// hand-written — Cloudflare's own guidance, and it makes a config/code mismatch a compile
// error rather than a runtime surprise.
//
// Only two things are augmented here, both deliberately absent from wrangler.jsonc:
//
//  - CONTENT_KEK: the Secrets Store binding that wraps content DEKs (ADR 22). Not yet
//    provisioned — Secrets Store needs a store id, which the install flow creates. Optional
//    so its absence is visible in the types; `evidence-store.ts` refuses to treat a missing
//    KEK as acceptable in production rather than falling back silently.
//  - TEST_MIGRATIONS: passed as a binding by vitest-pool-workers.
import type { D1Migration } from "@cloudflare/vitest-pool-workers";

declare global {
  interface Env {
    CONTENT_KEK?: { get(): Promise<string> };
  }
  namespace Cloudflare {
    interface Env {
      CONTENT_KEK?: { get(): Promise<string> };
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}
