/// <reference path="./node_modules/@cloudflare/vitest-pool-workers/types/cloudflare-test.d.ts" />

// `Env` itself is generated by `wrangler types` into worker-configuration.d.ts and is never
// hand-written — Cloudflare's own guidance, and it makes a config/code mismatch a compile
// error rather than a runtime surprise.
//
// The only addition here is test-only: vitest-pool-workers passes the migration list as a
// binding, and `cloudflare:test` types its `env` as `Cloudflare.Env`, so that is what needs
// augmenting.
import type { D1Migration } from "@cloudflare/vitest-pool-workers";

declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}
