/// <reference path="./node_modules/@cloudflare/vitest-pool-workers/types/cloudflare-test.d.ts" />

// `Env` is generated by `wrangler types` into worker-configuration.d.ts and never
// hand-written — Cloudflare's own guidance, and it makes a config/code mismatch a compile
// error rather than a runtime surprise.
//
// Only TEST_MIGRATIONS is augmented, passed as a binding by vitest-pool-workers. The CONTENT_KEK
// and CREDENTIAL_KEK Secrets Store bindings are gone: ADR 28 moved both root keys into the
// KeyVault Durable Object, which `wrangler types` generates from wrangler.jsonc like any other
// binding, so there is nothing to hand-declare.
import type { D1Migration } from "@cloudflare/vitest-pool-workers";

declare global {
  interface Env {
    /**
     * Cloudflare Email Sending. Optional in the type because a Node can exist without it — §14
     * requires "can this Node send" to be a *capability answer* rather than a crash, and
     * `transport.ts` reports its absence rather than throwing.
     */
    EMAIL?: {
      send(message: unknown): Promise<{ messageId?: string } | undefined>;
    };
  }
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}
