/**
 * Types for `/app/config.js` — the receipt-derived figures the browser is handed, generated by
 * `configModule()` in `src/ui.ts` and left external by `build-client.mjs`, like `/app/session.js` beside it.
 * Mapped onto the specifier by `src/client/tsconfig.json`'s `paths`, because TypeScript reads a leading
 * slash as a path on disk and an ambient `declare module` for it never matches.
 *
 * Hand-written, therefore capable of drifting from the module it describes — `tsc` cannot catch that.
 * `test/security-headers.test.ts` reads the generated module and asserts each field against the budget it
 * came from, which is the half a type cannot check.
 *
 * There are no optional fields and no `?? default` at the reader (#97). The values arrived on
 * `window.MAILDA_CONFIG` from an inline `<script>` until the CSP made that untenable, and a `window`
 * property that might be absent is what the fallbacks existed for. An import cannot be absent without the
 * module failing loudly, which is the honest failure for "the interface does not know its own numbers".
 */

export interface MaildaConfig {
  /** How early `session.client.js` refreshes an access token, from `docs/receipts/password-hash-cost.md`. */
  readonly refreshMarginSeconds: number;
  /** The non-`HttpOnly` cookie carrying the access token's expiry, so the client can see it coming. */
  readonly expiryCookie: string;
  /** How long a sealed send waits before dispatch — what the composer promises a person they can stop. */
  readonly holdWindowSeconds: number;
  /**
   * The attachments' base64 size a send may carry: the provider's receipted outbound ceiling times a provisional
   * 0.9 with no receipt (`src/outbound/attachment-budget.ts`).
   */
  readonly attachmentBudgetBytes: number;
  /** How many files a send may carry: provisional, with no receipt (`src/outbound/attachment-budget.ts`). */
  readonly maxAttachments: number;
  /** The most a copy (ADR 47) may be: `email.outbound.max_bytes`, Cloudflare's outbound ceiling, which the seal refuses past. */
  readonly outboundMaxBytes: number;
  /** How many destinations an address may forward to: `forward.max_destinations`, which the Node refuses past. */
  readonly forwardMaxDestinations: number;
}

export const CONFIG: MaildaConfig;
