import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { parseReceipt, ReceiptError, type Receipt } from "./parse.ts";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const receiptsDir = join(repoRoot, "docs/receipts");
const outputFile = join(repoRoot, "packages/budgets/src/generated.ts");

/**
 * Emits packages/budgets from docs/receipts.
 *
 * The point of this file is that a number cannot enter the codebase without a
 * measurement behind it — you write the receipt, and the constant follows. See
 * AGENTS.md, "Every number needs a receipt".
 */
async function main(): Promise<void> {
  const receipts = await readAll();
  const collisions = findCollisions(receipts);
  if (collisions.length > 0) {
    const detail = collisions
      .map(({ name, sources }) => `  ${name}\n    declared in ${sources.join("\n    declared in ")}`)
      .join("\n");
    throw new Error(
      `E_BUDGET_DECLARED_TWICE  ${collisions.length} budget name(s) declared by more than one receipt\n${detail}\n` +
        `  fix      a budget has exactly one measurement; merge the receipts or rename one budget`,
    );
  }

  await writeFile(outputFile, render(receipts), "utf8");
  const count = receipts.reduce((total, receipt) => total + Object.keys(receipt.values).length, 0);
  console.log(`receipts: ${receipts.length} file(s) -> ${count} budget(s) -> ${relative(repoRoot, outputFile)}`);
}

async function readAll(): Promise<Receipt[]> {
  let entries: string[];
  try {
    entries = await readdir(receiptsDir);
  } catch {
    return [];
  }

  const receipts: Receipt[] = [];
  for (const entry of entries.filter((name) => name.endsWith(".md")).sort()) {
    const path = join(receiptsDir, entry);
    const text = await readFile(path, "utf8");
    receipts.push(parseReceipt(relative(repoRoot, path), text));
  }
  return receipts;
}

function findCollisions(receipts: Receipt[]): Array<{ name: string; sources: string[] }> {
  const seen = new Map<string, string[]>();
  for (const receipt of receipts) {
    for (const name of Object.keys(receipt.values)) {
      const sources = seen.get(name) ?? [];
      sources.push(receipt.source);
      seen.set(name, sources);
    }
  }
  return [...seen.entries()]
    .filter(([, sources]) => sources.length > 1)
    .map(([name, sources]) => ({ name, sources }));
}

function render(receipts: Receipt[]): string {
  const lines: string[] = [
    "// GENERATED by @mailda/receipts from docs/receipts/*.md — do not edit.",
    "// A number here exists because something was measured. To change one, change its",
    "// receipt and re-run `pnpm receipts`. See AGENTS.md.",
    "",
    "export interface BudgetOrigin {",
    "  /** Receipt that established this number. */",
    "  readonly receipt: string;",
    "  readonly kind: string;",
    "  readonly measuredOn: string;",
    "  readonly staleWhen: string;",
    "}",
    "",
    "export const BUDGETS = {",
  ];

  for (const receipt of receipts) {
    for (const [name, value] of Object.entries(receipt.values).sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`  ${JSON.stringify(name)}: ${value},`);
    }
  }
  lines.push("} as const satisfies Record<string, number>;", "");

  lines.push("export type BudgetName = keyof typeof BUDGETS;", "");
  lines.push("/** Where each budget came from, so an error can name its receipt. */");
  lines.push("export const BUDGET_ORIGINS: Record<BudgetName, BudgetOrigin> = {");
  for (const receipt of receipts) {
    for (const name of Object.keys(receipt.values).sort()) {
      lines.push(
        `  ${JSON.stringify(name)}: { receipt: ${JSON.stringify(receipt.source)}, ` +
          `kind: ${JSON.stringify(receipt.kind)}, measuredOn: ${JSON.stringify(receipt.measuredOn)}, ` +
          `staleWhen: ${JSON.stringify(receipt.staleWhen)} },`,
      );
    }
  }
  lines.push("};", "");
  return lines.join("\n");
}

main().catch((error: unknown) => {
  if (error instanceof ReceiptError) {
    console.error(error.message);
  } else {
    console.error(error instanceof Error ? error.message : String(error));
  }
  process.exitCode = 1;
});
