import type { Ctx } from "@mailda/runtime";

/**
 * `Env` is deliberately **not** declared in this codebase.
 *
 * It is generated by `wrangler types` into `worker-configuration.d.ts` from the bindings
 * actually present in `wrangler.jsonc` — Cloudflare's own guidance — which makes a
 * config/code mismatch a compile error instead of a runtime surprise. An earlier version of
 * this file hand-wrote the interface and drifted within the hour: it lacked the Durable
 * Object binding the generated one had, and nothing complained.
 *
 * `Env` is global, so modules reference it without importing anything. Bindings that are
 * test-only or not yet provisioned are augmented in `env.d.ts`.
 */

/**
 * Everything a request needs, assembled once at the boundary.
 *
 * `ctx` carries time, randomness and id minting (#6). It is threaded explicitly rather than
 * reached for globally, because a module-level clock leaks across requests under isolate
 * reuse — and because §27's frozen-clock replay is then just an injection.
 */
export interface RequestContext {
  env: Env;
  ctx: Ctx;
  orgId: string;
}
