import { DurableObject } from "cloudflare:workers";

/**
 * Key custody (ADR 28).
 *
 * Both root keys are **generated by the Node, into this Durable Object's storage**, on first use.
 * There is no binding to configure, no secret to provision, and no way to install a Node that is
 * accidentally unprotected.
 *
 * ## Why not Secrets Store
 *
 * ADR 22 required credentials in Secrets Store so nothing sensitive sits on `env`. ADR 24 required
 * the Node's repository byte-identical across installs, because the repository *is* the update
 * channel. A `secrets_store_secrets` binding needs an account-specific `store_id` in committed
 * config, and — measured — removing it does **not** relink the way D1 and R2 do; the binding is
 * silently absent (receipt: `binding-relink-on-id-removal.md`).
 *
 * What settled it is ADR 7's own honesty constraint: with the KEK in Secrets Store, Cloudflare holds
 * ciphertext *and* key, so Secrets Store never protected against the platform. The only threat it
 * defended was **a D1 dump or a configuration leak**, and Durable Object storage sits outside D1 —
 * same protection, portable configuration. ADR 22's load-bearing property survives, because the key
 * arrives over RPC and is never a property of `env`.
 *
 * ## Generations, and why the legacy key cannot simply be deleted
 *
 * Keys are numbered. **Generation 0 is the published development constant** — the key existing
 * evidence on already-deployed Nodes was sealed under. Deleting the ability to *read* generation 0
 * would make that mail unreadable, so the legacy key survives as a **decrypt-only** path that can
 * never seal anything. It disappears for real once no generation-0 object remains, which `doctor`
 * counts and `reseal.ts` drives.
 *
 * Sealing always uses the highest generation. Opening uses whichever generation the object itself
 * records, which is what makes re-sealing incremental and interruptible rather than a flag day.
 *
 * ## The cost this design accepts
 *
 * This storage is the crown jewels. Lose it and every message is permanently unreadable, where a
 * managed secret store would have allowed re-provisioning. ADR 28 therefore does not ship without
 * the key escrow in ADR 29 — the same recovery codes that restore an account restore the vault, so
 * an operator has one artifact to keep rather than two to lose separately.
 *
 * **That escrow exists now** (#92, `src/recovery.ts`). For a while the sentence above was a shipping
 * condition satisfied by nothing, and worse: the refusals in this file told an operator to *"restore the
 * vault from the ADR 29 recovery codes"* when there were none to hold, so the remedy named was impossible.
 * `restore()` below is the method that puts a key back, `mintRecoveryCodes` writes the escrow at claim, and
 * doctor's `recovery_escrow` finding reports whether it is present **and current** — a stale escrow restores
 * a vault that can read old mail and not new, which is the failure that looks like success.
 */

export type KeyPurpose = "content" | "credential";

export interface VaultKey {
  generation: number;
  /** Raw 32 bytes, base64. Crosses the RPC boundary and is never stored on `env`. */
  secret: string;
}

/**
 * Generation 0: the constant that shipped before the vault existed.
 *
 * Published in this repository, therefore not a secret, therefore **decrypt-only**. It is here so
 * that mail already written can still be read, and `sealingKey()` will never return it.
 */
const LEGACY_GENERATION = 0;
const LEGACY_SECRETS: Record<KeyPurpose, string> = {
  content: "mailda-local-development-only-not-a-secret",
  credential: "mailda-local-development-only-credential-kek",
};

const CURRENT = (purpose: KeyPurpose) => `${purpose}:current`;
const AT = (purpose: KeyPurpose, generation: number) => `${purpose}:gen:${generation}`;

export class KeyVault extends DurableObject<Env> {
  /**
   * The key new objects are sealed under. Generates one on first call, so a fresh Node is protected
   * without a key ceremony — §5A's install flow has enough to get wrong already.
   *
   * `blockConcurrencyWhile` is what makes "generated once" true rather than likely: two concurrent
   * callers would otherwise both find no key and both write one, and the loser's objects would be
   * sealed under a key the vault no longer names as current.
   */
  async sealingKey(purpose: KeyPurpose): Promise<VaultKey> {
    const existing = await this.ctx.storage.get<number>(CURRENT(purpose));
    if (existing !== undefined) {
      const secret = await this.ctx.storage.get<string>(AT(purpose, existing));
      if (secret !== undefined) return { generation: existing, secret };
    }

    let created: VaultKey | null = null;
    await this.ctx.blockConcurrencyWhile(async () => {
      const generation = (await this.ctx.storage.get<number>(CURRENT(purpose))) ?? LEGACY_GENERATION;
      const stored = await this.ctx.storage.get<string>(AT(purpose, generation));
      if (stored !== undefined) {
        created = { generation, secret: stored };
        return;
      }
      const next = generation + 1;
      const secret = btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));
      // Key first, pointer second. The reverse order would let a reader see a `current` generation
      // whose key is not there yet.
      await this.ctx.storage.put(AT(purpose, next), secret);
      await this.ctx.storage.put(CURRENT(purpose), next);
      created = { generation: next, secret };
    });

    if (created === null) {
      throw new Error(
        `E_VAULT_NO_KEY  could not obtain a ${purpose} key\n` +
          "  why      the vault neither found nor created one\n" +
          "  fix      this Node cannot seal or open evidence; check Durable Object storage",
      );
    }
    return created;
  }

  /**
   * The key that opens an object sealed under a given generation.
   *
   * Returns the legacy constant for generation 0, which is the only reason a Node deployed before
   * the vault can still read its own mail.
   */
  async openingKey(purpose: KeyPurpose, generation: number): Promise<VaultKey> {
    if (generation === LEGACY_GENERATION) {
      return { generation: LEGACY_GENERATION, secret: LEGACY_SECRETS[purpose] };
    }
    const secret = await this.ctx.storage.get<string>(AT(purpose, generation));
    if (secret === undefined) {
      throw new Error(
        `E_VAULT_UNKNOWN_GENERATION  ${purpose} generation ${generation} is not in this vault\n` +
          "  why      an object records a key this Node has never held — a restored backup whose " +
          "Durable Object storage did not come with it, or the wrong Node\n" +
          "  fix      POST /api/recovery/redeem with one of the ten recovery codes printed at claim; " +
          "the data is intact but unreadable without its key",
      );
    }
    return { generation, secret };
  }

  /**
   * Rotates. The new generation seals; every earlier one still opens, which is what makes rotation
   * survivable rather than a flag day — the same shape ADR 27 uses for signing keys.
   */
  async rotate(purpose: KeyPurpose): Promise<{ from: number; to: number }> {
    let result = { from: LEGACY_GENERATION, to: LEGACY_GENERATION };
    await this.ctx.blockConcurrencyWhile(async () => {
      const from = (await this.ctx.storage.get<number>(CURRENT(purpose))) ?? LEGACY_GENERATION;
      const to = from + 1;
      const secret = btoa(String.fromCharCode(...crypto.getRandomValues(new Uint8Array(32))));
      await this.ctx.storage.put(AT(purpose, to), secret);
      await this.ctx.storage.put(CURRENT(purpose), to);
      result = { from, to };
    });
    return result;
  }

  /**
   * Puts a generation's key back, from ADR 29's escrow (#92).
   *
   * This is the method that turns *"lose it and every message is permanently unreadable"* into a sentence
   * with an escape. Everything else here **generates** keys; nothing could put a known one back, which is
   * why three refusals in this file and in `doctor` named a remedy that did not exist.
   *
   * ## It never overwrites, and that is the whole safety argument
   *
   * A restore is run during an incident, by somebody who may not be certain what state this vault is in. If
   * it overwrote, a code redeemed against a *healthy* vault — a mistake made under pressure — would replace
   * live keys with older copies, and objects sealed since the escrow was taken would become unreadable. That
   * is the failure mode of the mechanism meant to prevent exactly it.
   *
   * So a generation already present is left alone and reported as untouched. Restoring is therefore
   * idempotent and safe to repeat, which is the property somebody re-running a half-finished recovery needs.
   *
   * `blockConcurrencyWhile` for `sealingKey`'s reason: the check and the write have to be one step, or two
   * concurrent restores can both find a generation absent.
   */
  async restore(
    purpose: KeyPurpose, generation: number, secret: string,
  ): Promise<"restored" | "identical" | "conflict"> {
    if (generation === LEGACY_GENERATION) {
      /*
       * Generation 0 is the published development constant and `openingKey` returns it without storage.
       * Writing it would put a value from a public repository into the place this Node keeps its secrets, and
       * a later reader would have no way to tell it from a real one.
       */
      return "identical";
    }
    let outcome: "restored" | "identical" | "conflict" = "identical";
    await this.ctx.blockConcurrencyWhile(async () => {
      const present = await this.ctx.storage.get<string>(AT(purpose, generation));
      if (present !== undefined) {
        /*
         * **A generation already here with a *different* secret is a real state, and it is the one worth
         * refusing to paper over.** Reachable, and measured: wipe this storage, let the Node keep working,
         * and `sealingKey` mints a fresh generation 1 — a different secret under the same number. An escrow
         * taken before the wipe then carries generation 1 too, and the two are both needed: objects sealed
         * before the loss open with one, objects sealed after with the other.
         *
         * Nothing can hold both under one number, so this keeps the **live** key — which preserves the newer
         * mail — and reports the collision rather than resolving it in silence. Overwriting would trade
         * newer mail for older; skipping quietly, which is what the first version did, told the operator the
         * generation had been restored when it had not.
         */
        outcome = present === secret ? "identical" : "conflict";
        return;
      }
      await this.ctx.storage.put(AT(purpose, generation), secret);
      /*
       * The pointer moves only forward. A restore that lowered `current` would make this Node seal *new*
       * mail under an old key — which is not a recovery, it is a quiet downgrade of every message written
       * afterwards. Key first, pointer second, as everywhere else in this file.
       */
      const current = (await this.ctx.storage.get<number>(CURRENT(purpose))) ?? LEGACY_GENERATION;
      if (generation > current) await this.ctx.storage.put(CURRENT(purpose), generation);
      outcome = "restored";
    });
    return outcome;
  }

  /** What the vault holds, for `doctor`. Generations only — never key material. */
  async inventory(): Promise<{ content: number; credential: number }> {
    return {
      content: (await this.ctx.storage.get<number>(CURRENT("content"))) ?? LEGACY_GENERATION,
      credential: (await this.ctx.storage.get<number>(CURRENT("credential"))) ?? LEGACY_GENERATION,
    };
  }
}

/** The one vault. A second instance would be a second set of keys and a silent data loss. */
export function vault(env: Env) {
  return env.KEY_VAULT.getByName("node");
}

/**
 * Derives an AES-GCM key from a vault secret.
 *
 * Kept here rather than in each caller so there is exactly one place where a secret becomes a
 * CryptoKey, and so `extractable: false` is not something each caller has to remember.
 */
export async function aesKeyFrom(secret: string): Promise<CryptoKey> {
  const material = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(secret));
  return crypto.subtle.importKey("raw", material, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]);
}

export const LEGACY_KEY_GENERATION = LEGACY_GENERATION;
