// GENERATED by @mailda/receipts from docs/receipts/*.md — do not edit.
// A number here exists because something was measured. To change one, change its
// receipt and re-run `pnpm receipts`. See AGENTS.md.

export interface BudgetOrigin {
  /** Receipt that established this number. */
  readonly receipt: string;
  readonly kind: string;
  readonly measuredOn: string;
  readonly staleWhen: string;
}

export const BUDGETS = {
  "authz.check.max_queries": 2,
  "authz.check.max_rows_read": 200,
  "authz.list.max_rows_read": 1000,
  "d1.free.max_account_storage_bytes": 5368709120,
  "d1.free.max_database_bytes": 524288000,
  "d1.free.max_queries_per_invocation": 50,
  "d1.free.time_travel_days": 7,
  "d1.max_bound_parameters": 100,
  "d1.max_columns_per_table": 100,
  "d1.max_query_duration_seconds": 30,
  "d1.max_row_bytes": 2000000,
  "d1.max_sql_function_args": 32,
  "d1.max_sql_statement_bytes": 100000,
  "d1.max_time_travel_restores_per_10min": 10,
  "d1.paid.max_account_storage_bytes": 1099511627776,
  "d1.paid.max_database_bytes": 10737418240,
  "d1.paid.max_databases_per_account": 50000,
  "d1.paid.max_queries_per_invocation": 1000,
  "d1.paid.time_travel_days": 30,
  "message.metadata.bytes_per_extra_delivery": 467,
  "message.metadata.bytes_per_message": 1253,
  "shard.plan_route_messages": 7709970,
  "shard.plan_stop_messages": 7281638,
  "shard.plan_warn_messages": 5996643,
} as const satisfies Record<string, number>;

export type BudgetName = keyof typeof BUDGETS;

/** Where each budget came from, so an error can name its receipt. */
export const BUDGET_ORIGINS: Record<BudgetName, BudgetOrigin> = {
  "authz.check.max_queries": { receipt: "docs/receipts/authz-check-rows-read.md", kind: "measured-tripwire", measuredOn: "2026-08-03", staleWhen: "the relationship_tuples or team_members index definitions change; a team-membership model beyond user->team->object is introduced; or ABAC/policy conditions begin reading additional rows on the request path" },
  "authz.check.max_rows_read": { receipt: "docs/receipts/authz-check-rows-read.md", kind: "measured-tripwire", measuredOn: "2026-08-03", staleWhen: "the relationship_tuples or team_members index definitions change; a team-membership model beyond user->team->object is introduced; or ABAC/policy conditions begin reading additional rows on the request path" },
  "authz.list.max_rows_read": { receipt: "docs/receipts/authz-check-rows-read.md", kind: "measured-tripwire", measuredOn: "2026-08-03", staleWhen: "the relationship_tuples or team_members index definitions change; a team-membership model beyond user->team->object is introduced; or ABAC/policy conditions begin reading additional rows on the request path" },
  "d1.free.max_account_storage_bytes": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.free.max_database_bytes": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.free.max_queries_per_invocation": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.free.time_travel_days": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.max_bound_parameters": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.max_columns_per_table": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.max_query_duration_seconds": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.max_row_bytes": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.max_sql_function_args": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.max_sql_statement_bytes": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.max_time_travel_restores_per_10min": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.paid.max_account_storage_bytes": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.paid.max_database_bytes": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.paid.max_databases_per_account": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.paid.max_queries_per_invocation": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "d1.paid.time_travel_days": { receipt: "docs/receipts/d1-platform-limits.md", kind: "platform-limit", measuredOn: "2026-08-02", staleWhen: "automatic resource provisioning or read replication leaves beta; the published D1 limits page changes (last moved 2026-04-21); or D1 gains interactive transactions" },
  "message.metadata.bytes_per_extra_delivery": { receipt: "docs/receipts/message-metadata-bytes.md", kind: "measured-tripwire", measuredOn: "2026-08-03", staleWhen: "the messages or mailbox_items schema changes, an index is added or removed, the identifier scheme changes width (#6), or D1's per-database ceiling moves from 10 GB" },
  "message.metadata.bytes_per_message": { receipt: "docs/receipts/message-metadata-bytes.md", kind: "measured-tripwire", measuredOn: "2026-08-03", staleWhen: "the messages or mailbox_items schema changes, an index is added or removed, the identifier scheme changes width (#6), or D1's per-database ceiling moves from 10 GB" },
  "shard.plan_route_messages": { receipt: "docs/receipts/message-metadata-bytes.md", kind: "measured-tripwire", measuredOn: "2026-08-03", staleWhen: "the messages or mailbox_items schema changes, an index is added or removed, the identifier scheme changes width (#6), or D1's per-database ceiling moves from 10 GB" },
  "shard.plan_stop_messages": { receipt: "docs/receipts/message-metadata-bytes.md", kind: "measured-tripwire", measuredOn: "2026-08-03", staleWhen: "the messages or mailbox_items schema changes, an index is added or removed, the identifier scheme changes width (#6), or D1's per-database ceiling moves from 10 GB" },
  "shard.plan_warn_messages": { receipt: "docs/receipts/message-metadata-bytes.md", kind: "measured-tripwire", measuredOn: "2026-08-03", staleWhen: "the messages or mailbox_items schema changes, an index is added or removed, the identifier scheme changes width (#6), or D1's per-database ceiling moves from 10 GB" },
};
