import type { Ctx } from "@mailda/runtime";
import { probeCredentialKey } from "../auth/kek.ts";
import { mintAccessToken, verifyAccessToken } from "../auth/jwt.ts";
import { vault } from "../keyvault.ts";
import { pendingReseal } from "../reseal.ts";
import { type Finding } from "../doctor.ts";
/**
 * The vault (ADR 28).
 *
 * There is no binding to be absent any more, which is the point: a Node generates its own keys on
 * first use, so "encrypted under a constant published in the public repository" stopped being a
 * representable state rather than one this function has to catch. What is left to check is whether
 * any evidence is *still* at generation 0 from before the vault existed — which is a migration in
 * progress, not a misconfiguration, so it is `degraded` and names the remedy.
 */
export async function checkVault(env: Env): Promise<Finding[]> {
  let inventory: { content: number; credential: number };
  try {
    // Deliberately `sealingKey`, not `inventory` — this **initialises** the vault if it is empty.
    //
    // A diagnostic that mutates needs a reason, and here it is: generation-0 evidence can only be
    // *detected* by comparing it against a newer key, so a Node that predates the vault would never
    // learn it has a backlog until something happened to seal. Generating is idempotent, and
    // `sealingKey` never returns the legacy constant, so this cannot create an unprotected state.
    // `ensureKey`, not `sealingKey`: this initialises the vault and seals nothing, so the generation it
    // mints stays *reserved* rather than load-bearing — which is what lets an escrowed key of the same
    // number take its place during a restore (#138). Marking it used here made the documented recovery
    // path unable to install the escrow on any fresh Node.
    const content = await vault(env).ensureKey("content");
    const credential = await vault(env).ensureKey("credential");
    inventory = { content: content.generation, credential: credential.generation };
  } catch (error) {
    return [{
      check: "key_vault",
      severity: "refuse",
      discloses: "infrastructure",
      ok: false,
      detail: `The KeyVault Durable Object did not answer: ${(error as Error).message.split("\n")[0]}`,
      fix: "check the KEY_VAULT durable_objects binding and the migrations tag declaring the class; " +
        "without it this Node can neither seal nor open evidence",
    }];
  }

  const findings: Finding[] = [{
    check: "key_vault",
    severity: "refuse",
    discloses: "infrastructure",
    ok: true,
    detail: `content key generation ${inventory.content}, credential key generation ${inventory.credential}. ` +
      `Generated by this Node; generation 0 is the published constant and is decrypt-only.`,
  }];

  const behind = await pendingReseal(env, inventory.content).catch(() => null);
  if (behind !== null && behind > 0) {
    findings.push({
      check: "evidence_key_generation",
      severity: "degraded",
      discloses: "data",
      ok: false,
      detail: `${behind} receipt(s) reference evidence sealed under an older key generation. ` +
        `Generation 0 is a constant published in the Mailda repository, so that mail is not protected.`,
      fix: "POST /api/maintenance/reseal repeatedly until `remaining` reaches 0; it is resumable and " +
        "verifies each message against its recorded plaintext SHA-256",
      receipt: "docs/receipts/evidence-lifecycle.md",
    });
  }

  return findings;
}


/**
 * The credential key, checked by **using** it rather than by looking at it.
 *
 * There is no binding to be present any more (ADR 28), so the failure this catches has changed shape:
 * a wrap/unwrap round trip fails when the vault holds a different key than the one that wrapped an
 * existing value — a restored backup whose Durable Object storage did not come with it, or a rotation
 * that was interrupted. Presence was never the interesting question; usability is.
 */
export async function checkCredentialKek(env: Env): Promise<Finding[]> {
  try {
    // `probeCredentialKey`, not `wrapCredential`: a diagnostic that wraps a constant and discards it seals
    // nothing, and marking the generation used made the escrow unable to install on a fresh Node (#138).
    const recovered = await probeCredentialKey(env);
    return [{
      check: "credential_key",
      severity: "refuse",
      discloses: "infrastructure",
      ok: recovered,
      detail: recovered
        ? "Wrap/unwrap round trip succeeded."
        : "Wrap/unwrap round trip returned different bytes.",
      ...(recovered ? {} : {
        fix: "the credential key changed; existing signing keys cannot be unwrapped and must be rotated",
      }),
    }];
  } catch (error) {
    return [{
      check: "credential_key",
      severity: "refuse",
      discloses: "infrastructure",
      ok: false,
      detail: `Could not wrap and unwrap with the credential key: ${(error as Error).message.split("\n")[0]}`,
      fix: "if the vault reports an unknown generation, restore it with POST /api/recovery/redeem — " +
        "the data is intact but unreadable without its key",
    }];
  }
}


/**
 * Signing keys, also checked by using them: mint a token and verify it.
 *
 * Absence is `degraded`, not `refuse` — a key is generated on first use, so an empty table
 * self-heals on the next sign-in. A key that exists and cannot sign or verify does not.
 */
export async function checkSigningKeys(env: Env, ctx: Ctx): Promise<Finding[]> {
  const counts = await env.CATALOG.prepare(
    `SELECT
       SUM(CASE WHEN status = 'current'  THEN 1 ELSE 0 END) AS current_keys,
       SUM(CASE WHEN status = 'retiring' THEN 1 ELSE 0 END) AS retiring_keys
     FROM signing_keys`,
  ).first<{ current_keys: number | null; retiring_keys: number | null }>().catch(() => null);

  const current = counts?.current_keys ?? 0;
  if (current === 0) {
    return [{
      check: "signing_key",
      severity: "degraded",
      discloses: "infrastructure",
      ok: false,
      detail: "No current signing key. One is generated on the next sign-in, so this self-heals — but no existing access token can be verified until then.",
      fix: "sign in once, or POST /api/auth/rotate-signing-key",
    }];
  }

  try {
    const minted = await mintAccessToken(env, ctx, { orgId: "org_doctor", userId: "usr_doctor" });
    const verified = await verifyAccessToken(env, minted.token, ctx.now());
    return [{
      check: "signing_key",
      severity: "refuse",
      discloses: "infrastructure",
      ok: verified.ok,
      detail: verified.ok
        ? `Sign and verify round trip succeeded. ${current} current, ${counts?.retiring_keys ?? 0} still verifying.`
        : `A token signed by the current key does not verify: ${verified.reason}.`,
      ...(verified.ok ? {} : { fix: "rotate the signing key; sign-in cannot work while this fails" }),
    }];
  } catch (error) {
    return [{
      check: "signing_key",
      severity: "refuse",
      discloses: "infrastructure",
      ok: false,
      detail: `Could not use the current signing key: ${(error as Error).message.split("\n")[0]}`,
      fix: "the key is unwrappable only with the credential key that wrapped it — check the credential_key finding first",
    }];
  }
}
